using FabricationAssistant.App.Android;
using FabricationAssistant.Core.Math;
using FabricationAssistant.Core.SceneGraph;
using Xunit;

namespace FabricationAssistant.App.Android.Tests;

public sealed class AndroidModelSelectionResolverTests
{
    [Fact]
    public void PartModeResolvesMeshChildToOwningPart()
    {
        Scene scene = CreateSceneWithMultiMeshPart();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [11],
            AndroidModelSelectionMode.Part);

        Assert.Equal([10], selectedNodeIds);
    }

    [Fact]
    public void MeshModeKeepsExactMeshNode()
    {
        Scene scene = CreateSceneWithMultiMeshPart();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [11],
            AndroidModelSelectionMode.Mesh);

        Assert.Equal([11], selectedNodeIds);
    }

    [Fact]
    public void RenderableNodesExpandLogicalPartToAllMeshes()
    {
        Scene scene = CreateSceneWithMultiMeshPart();

        int[] renderableNodeIds = AndroidModelSelectionResolver.ResolveRenderableNodeIds(scene, [10]);

        Assert.Equal([11, 12], renderableNodeIds);
    }

    [Fact]
    public void VisibleLogicalCountCollapsesMultiMeshPartInPartMode()
    {
        Scene scene = CreateSceneWithMultiMeshPart();

        Assert.Equal(1, AndroidModelSelectionResolver.CountVisibleLogicalNodes(scene, AndroidModelSelectionMode.Part));
        Assert.Equal(2, AndroidModelSelectionResolver.CountVisibleLogicalNodes(scene, AndroidModelSelectionMode.Mesh));
    }

    [Fact]
    public void PartModeCollapsesAutoGeneratedMeshNodeToPresentedOwner()
    {
        Scene scene = CreateSceneWithPresentedOwner();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [21],
            AndroidModelSelectionMode.Part);

        Assert.Equal([20], selectedNodeIds);

        int[] meshNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [21],
            AndroidModelSelectionMode.Mesh);
        Assert.Equal([21], meshNodeIds);
    }

    [Fact]
    public void PartModeCollapsesSameSourceKeySubtreeToPresentedOwner()
    {
        Scene scene = CreateSceneWithPresentedOwner();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [22],
            AndroidModelSelectionMode.Part);

        Assert.Equal([20], selectedNodeIds);
    }

    [Fact]
    public void PartModeCollapsesAutoGeneratedPartLeafBeforeOwningPartResolution()
    {
        Scene scene = CreateSceneWithPresentedOwner();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [23],
            AndroidModelSelectionMode.Part);

        Assert.Equal([20], selectedNodeIds);

        int[] meshNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [23],
            AndroidModelSelectionMode.Mesh);
        Assert.Equal([23], meshNodeIds);
    }

    [Fact]
    public void AssemblyModeResolvesMeshToNearestOwningAssembly()
    {
        Scene scene = CreateSceneWithNestedAssemblies();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [4],
            AndroidModelSelectionMode.Assembly);

        // A1 (id 2), the nearest assembly — not the top assembly A (id 1).
        Assert.Equal([2], selectedNodeIds);
    }

    [Fact]
    public void AssemblyModeFallsBackToOwningPartWhenNoAssemblyAncestor()
    {
        Scene scene = CreateSceneWithMultiMeshPart();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [11],
            AndroidModelSelectionMode.Assembly);

        Assert.Equal([10], selectedNodeIds);
    }

    [Fact]
    public void AssemblyModeResolvesAssemblyDirectGeometryToOwningAssembly()
    {
        Scene scene = CreateSceneWithAssemblyDirectBodies();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [31],
            AndroidModelSelectionMode.Assembly);

        Assert.Equal([30], selectedNodeIds);
    }

    [Fact]
    public void PartModeKeepsAssemblyDirectBodyAsItsOwnEntity()
    {
        Scene scene = CreateSceneWithAssemblyDirectBodies();

        int[] selectedNodeIds = AndroidModelSelectionResolver.ResolveNodeIds(
            scene,
            [31],
            AndroidModelSelectionMode.Part);

        // A distinct-named body directly under an assembly has no Part ancestor,
        // so Part mode keeps it as its own logical entity.
        Assert.Equal([31], selectedNodeIds);
    }

    [Fact]
    public void RenderableNodesExpandAssemblyToAllDescendantMeshes()
    {
        Scene scene = CreateSceneWithNestedAssemblies();

        int[] renderableNodeIds = AndroidModelSelectionResolver.ResolveRenderableNodeIds(scene, [1]);

        Assert.Equal([4], renderableNodeIds);
    }

    private static Scene CreateSceneWithMultiMeshPart()
    {
        var document = new DocumentDto();
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 0,
            ParentId = -1,
            DisplayName = "Root",
            NodeType = SceneNodeType.Root,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 10,
            ParentId = 0,
            DisplayName = "Part A",
            NodeType = SceneNodeType.Part,
        });
        document.Nodes.Add(CreateShapeNode(11, 10, "Mesh A1"));
        document.Nodes.Add(CreateShapeNode(12, 10, "Mesh A2"));
        document.Meshes.Add(CreateMesh(11));
        document.Meshes.Add(CreateMesh(12));

        return Scene.FromDocument(document);
    }

    private static Scene CreateSceneWithPresentedOwner()
    {
        var document = new DocumentDto();
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 0,
            ParentId = -1,
            DisplayName = "Root",
            NodeType = SceneNodeType.Root,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 20,
            ParentId = 0,
            DisplayName = "Logical Bracket",
            SourceNodeName = "Logical Bracket",
            NodeType = SceneNodeType.Instance,
            Metadata = new SceneNodeMetadataDto
            {
                SourceKey = "BRACKET-001",
            },
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 21,
            ParentId = 20,
            DisplayName = "Node 68",
            NodeType = SceneNodeType.Shape,
            MeshId = 21,
            Metadata = new SceneNodeMetadataDto
            {
                SourceKey = "BRACKET-001",
            },
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 22,
            ParentId = 20,
            DisplayName = "Imported primitive",
            SourceNodeName = "Imported primitive",
            NodeType = SceneNodeType.Shape,
            MeshId = 22,
            Metadata = new SceneNodeMetadataDto
            {
                SourceKey = "BRACKET-001",
            },
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 24,
            ParentId = 20,
            DisplayName = "Node 156",
            NodeType = SceneNodeType.Assembly,
            Metadata = new SceneNodeMetadataDto
            {
                SourceKey = "BRACKET-001",
            },
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 23,
            ParentId = 24,
            DisplayName = "Node 155",
            NodeType = SceneNodeType.Part,
            MeshId = 23,
            Metadata = new SceneNodeMetadataDto
            {
                SourceKey = "BRACKET-001",
            },
        });
        document.Meshes.Add(CreateMesh(21));
        document.Meshes.Add(CreateMesh(22));
        document.Meshes.Add(CreateMesh(23));

        return Scene.FromDocument(document);
    }

    private static Scene CreateSceneWithNestedAssemblies()
    {
        var document = new DocumentDto();
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 0,
            ParentId = -1,
            DisplayName = "Root",
            NodeType = SceneNodeType.Root,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 1,
            ParentId = 0,
            DisplayName = "Assembly A",
            SourceNodeName = "Assembly A",
            NodeType = SceneNodeType.Assembly,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 2,
            ParentId = 1,
            DisplayName = "Assembly A1",
            SourceNodeName = "Assembly A1",
            NodeType = SceneNodeType.Assembly,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 3,
            ParentId = 2,
            DisplayName = "Part P1",
            SourceNodeName = "Part P1",
            NodeType = SceneNodeType.Part,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 4,
            ParentId = 3,
            DisplayName = "Body",
            SourceNodeName = "Body",
            NodeType = SceneNodeType.Shape,
            MeshId = 4,
        });
        document.Meshes.Add(CreateMesh(4));

        return Scene.FromDocument(document);
    }

    private static Scene CreateSceneWithAssemblyDirectBodies()
    {
        var document = new DocumentDto();
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 0,
            ParentId = -1,
            DisplayName = "Root",
            NodeType = SceneNodeType.Root,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 30,
            ParentId = 0,
            DisplayName = "Assembly",
            SourceNodeName = "Assembly",
            NodeType = SceneNodeType.Assembly,
        });
        document.Nodes.Add(new SceneNodeDto
        {
            Id = 31,
            ParentId = 30,
            DisplayName = "Bracket",
            SourceNodeName = "Bracket",
            NodeType = SceneNodeType.Shape,
            MeshId = 31,
        });
        document.Meshes.Add(CreateMesh(31));

        return Scene.FromDocument(document);
    }

    private static SceneNodeDto CreateShapeNode(int id, int parentId, string displayName)
        => new()
        {
            Id = id,
            ParentId = parentId,
            DisplayName = displayName,
            NodeType = SceneNodeType.Shape,
            MeshId = id,
        };

    private static MeshDto CreateMesh(int id)
        => new()
        {
            MeshId = id,
            Bounds = new BoundingBox(new Vector3d(id, 0.0, 0.0), new Vector3d(id + 1.0, 1.0, 1.0)),
        };
}
