<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <SupportedOSPlatformVersion></SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifier></RuntimeIdentifier>
    <RuntimeIdentifiers></RuntimeIdentifiers>
    <Platforms>AnyCPU</Platforms>
    <Platform>AnyCPU</Platform>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
