using FabricationAssistant.Core.SceneGraph;

namespace FabricationAssistant.App.Android;

internal enum AndroidModelSelectionMode
{
    Part = 0,
    Mesh = 1,
    Assembly = 2,
}

internal static class AndroidModelSelectionResolver
{
    public static int[] ResolveNodeIds(
        Scene scene,
        IEnumerable<int> sourceNodeIds,
        AndroidModelSelectionMode mode)
    {
        ArgumentNullException.ThrowIfNull(scene);
        ArgumentNullException.ThrowIfNull(sourceNodeIds);

        return sourceNodeIds
            .Select(id => scene.GetNode(id))
            .Where(node => node is not null)
            .Select(node => ResolveNode(scene, node!, mode).Id)
            .Distinct()
            .OrderBy(id => id)
            .ToArray();
    }

    public static SceneNode ResolveNode(
        Scene scene,
        SceneNode sourceNode,
        AndroidModelSelectionMode mode)
    {
        ArgumentNullException.ThrowIfNull(scene);
        ArgumentNullException.ThrowIfNull(sourceNode);

        if (mode == AndroidModelSelectionMode.Mesh)
            return sourceNode;

        SceneNode presentedOwner = FindPresentedOwner(sourceNode) ?? sourceNode;

        if (mode == AndroidModelSelectionMode.Assembly)
            return FindOwningAssembly(presentedOwner)
                   ?? FindOwningPart(presentedOwner)
                   ?? presentedOwner;

        return FindOwningPart(presentedOwner) ?? presentedOwner;
    }

    public static int ResolveNodeId(Scene scene, SceneNode sourceNode, AndroidModelSelectionMode mode)
        => ResolveNode(scene, sourceNode, mode).Id;

    /// <summary>
    /// Returns the node the Model Explorer presents for <paramref name="node"/>
    /// (collapsing split-material shapes, auto-generated nodes, and same-source-key
    /// subtrees into their visible owner). Shared with the properties panel so the
    /// presented-owner walk lives in exactly one place.
    /// </summary>
    public static SceneNode ResolvePresentedOwner(SceneNode node)
    {
        ArgumentNullException.ThrowIfNull(node);
        return FindPresentedOwner(node) ?? node;
    }

    public static int[] ResolveRenderableNodeIds(Scene scene, IEnumerable<int> selectionNodeIds)
    {
        ArgumentNullException.ThrowIfNull(scene);
        ArgumentNullException.ThrowIfNull(selectionNodeIds);

        var renderableNodeIds = new HashSet<int>();
        foreach (int nodeId in selectionNodeIds)
        {
            SceneNode? node = scene.GetNode(nodeId);
            if (node is null)
                continue;

            CollectRenderableNodeIds(node, renderableNodeIds);
        }

        return renderableNodeIds
            .OrderBy(id => id)
            .ToArray();
    }

    public static int[] ResolveVisibleLogicalNodeIds(Scene scene, AndroidModelSelectionMode mode)
    {
        ArgumentNullException.ThrowIfNull(scene);

        return scene.GetVisibleNodes()
            .Select(node => ResolveNodeId(scene, node, mode))
            .Distinct()
            .OrderBy(id => id)
            .ToArray();
    }

    public static int CountVisibleLogicalNodes(Scene scene, AndroidModelSelectionMode mode)
        => ResolveVisibleLogicalNodeIds(scene, mode).Length;

    public static bool ShouldCollapseIntoPresentedOwner(SceneNode node, SceneNode visibleOwner)
    {
        ArgumentNullException.ThrowIfNull(node);
        ArgumentNullException.ThrowIfNull(visibleOwner);

        if (node.Parent is null)
            return false;

        if (IsSplitMaterialPrimitiveShape(node, visibleOwner))
            return true;

        if (string.IsNullOrWhiteSpace(node.SourceNodeName)
            && IsAutoGeneratedNodeLabel(node.DisplayName)
            && HasPresentedOwnerSignal(visibleOwner))
        {
            return true;
        }

        string? ownerSourceKey = visibleOwner.Metadata?.SourceKey;
        if (string.IsNullOrWhiteSpace(ownerSourceKey))
            return false;

        return SubtreeBelongsToSourceKey(node, ownerSourceKey);
    }

    private static SceneNode? FindOwningPart(SceneNode sourceNode)
    {
        for (SceneNode? current = sourceNode; current is not null; current = current.Parent)
        {
            if (current.NodeType == SceneNodeType.Part)
                return current;
        }

        return null;
    }

    private static SceneNode? FindOwningAssembly(SceneNode sourceNode)
    {
        // Nearest enclosing assembly. Instance nodes are occurrence wrappers,
        // not assemblies, so they are intentionally skipped here; when no
        // Assembly ancestor exists the caller falls back to Part resolution.
        for (SceneNode? current = sourceNode; current is not null; current = current.Parent)
        {
            if (current.NodeType == SceneNodeType.Assembly)
                return current;
        }

        return null;
    }

    private static SceneNode? FindPresentedOwner(SceneNode sourceNode)
    {
        SceneNode presented = sourceNode;
        while (presented.Parent is { } parent)
        {
            if (!parent.Children.Contains(presented)
                || !ShouldCollapseIntoPresentedOwner(presented, parent))
            {
                break;
            }

            presented = parent;
        }

        return presented;
    }

    private static void CollectRenderableNodeIds(SceneNode node, HashSet<int> target)
    {
        if (node.MeshId.HasValue)
            target.Add(node.Id);

        foreach (SceneNode child in node.Children)
            CollectRenderableNodeIds(child, target);
    }

    private static bool IsSplitMaterialPrimitiveShape(SceneNode node, SceneNode visibleOwner)
    {
        return ReferenceEquals(node.Parent, visibleOwner)
               && node.NodeType == SceneNodeType.Shape
               && visibleOwner.NodeType == SceneNodeType.Part
               && visibleOwner.MeshId is null
               && node.MeshId.HasValue;
    }

    private static bool SubtreeBelongsToSourceKey(SceneNode node, string ownerSourceKey)
    {
        string? nodeSourceKey = node.Metadata?.SourceKey;
        if (!string.IsNullOrWhiteSpace(nodeSourceKey)
            && !string.Equals(nodeSourceKey, ownerSourceKey, StringComparison.Ordinal))
        {
            return false;
        }

        foreach (SceneNode child in node.Children)
        {
            if (!SubtreeBelongsToSourceKey(child, ownerSourceKey))
                return false;
        }

        return true;
    }

    private static bool HasPresentedOwnerSignal(SceneNode owner)
    {
        if (owner.NodeType != SceneNodeType.Root)
            return true;

        return !string.IsNullOrWhiteSpace(owner.SourceNodeName)
               || !string.IsNullOrWhiteSpace(owner.Metadata?.SourceKey)
               || !string.IsNullOrWhiteSpace(owner.Metadata?.SourceType)
               || !string.IsNullOrWhiteSpace(owner.Metadata?.OccurrenceId);
    }

    private static bool IsAutoGeneratedNodeLabel(string displayName)
    {
        if (!displayName.StartsWith("Node ", StringComparison.OrdinalIgnoreCase))
            return false;

        ReadOnlySpan<char> suffix = displayName.AsSpan(5).Trim();
        if (suffix.IsEmpty)
            return false;

        foreach (char ch in suffix)
        {
            if (!char.IsAsciiDigit(ch))
                return false;
        }

        return true;
    }
}
